### ISSUE TITLE
DesignMode broken

### ISSUE THREAD

**Issue by quicoli** [quicoli/LottieSharp#1]
The sample in design mode was raising an exception in Visual Studio designer, blocking the view of the mainwindow xaml.  To fix,  change the LottieAnimationView.LottieAnimationView() to this:

        public LottieAnimationView()
        {
            _lottieDrawable = new LottieDrawable();

            if (!DesignerProperties.GetIsInDesignMode(this))
            {
                if (!string.IsNullOrEmpty(FileName))
                {
                    SetAnimationAsync(FileName).RunSynchronously();
                }
                else if (!string.IsNullOrEmpty(Url))
                {
                    SetAnimationFromUrlAsync(Url).RunSynchronously();
                }

                if (AutoPlay)
                {
                    _lottieDrawable.PlayAnimation();
                }
            }

            _lottieDrawable.RepeatCount = RepeatCount;

            EnableMergePathsForKitKatAndAbove(false);

            SimpleColorFilter filter = new SimpleColorFilter(ColorFilter);
            KeyPath keyPath = new KeyPath("**");
            var callback = new LottieValueCallback<ColorFilter>(filter);
            AddValueCallback(keyPath, LottieProperty.ColorFilter, callback);

            EnableOrDisableHardwareLayer();
        }

I just moved the "if (AutoPlay") to be executed only if not in design mode.

BTW, do you have tasks for this project? I'd like to help you.

**Comment by OmidID** [comment]
@quicoli Please make a pull request for that. Thanks
