### ISSUE TITLE
Memory Consumption is too much for the animation.

### ISSUE THREAD

**Issue by DevAtomWindows** [quicoli/LottieSharp#10]
I added a a json file from the stock lottie animations on their website. On running the application, the app was consuming a total of 70MB memory. Within a minute, it shooted to 100MB.

**To Reproduce**

1. Create a new project and Install the package via nuget.
2. Extract and add the following to your bin/Assets folder.

[phone_number_verification.zip](https://github.com/ascora/LottieSharp/files/2888950/phone_number_verification.zip)

3. Add this to MainWindow.xaml

```
<lottieSharp:LottieAnimationView Height="200" Width="200"
            DefaultCacheStrategy="None" 
            FileName="Assets/phone_number_verification.json" AutoPlay="True" 
            VerticalAlignment="Top" 
            HorizontalAlignment="Left"/>
```

3. Run the app
4. Open Resource Monitor and check the memory of your app being increased gradually.

**Comment by OmidID** [comment]
@DevAtomWindows Thanks for report
I leave that running for 30 minutes. it's started with 102 mb and remains same
![image](https://user-images.githubusercontent.com/956077/53182785-dbfaec00-3602-11e9-9d7b-7d04ef57a650.png)

Please test it again using builtin example application

**Comment by DevAtomWindows** [comment]
Don't you think 102 MB is a bit too much?

**Comment by Akku** [comment]
WPF animations often use a lot of memory. I think it's a downside, and this issue a suggestion for an enhancement.

**Comment by OmidID** [comment]
@DevAtomWindows Yes it is. But Lottie structure need lot of memory. I did the same test with LottieUWP and the result it was same 90MB and it's consume less because UWP applications are using less memory compare with WPF.
