### ISSUE TITLE
.Net 4.6 support

### ISSUE THREAD

**Issue by MarcIsele** [quicoli/LottieSharp#13]
Hi,
I would like to use Lottie with .Net version 4.6.
Is there a specific reason why you are targetting .Net 4.6.1 or can I just compile using 4.6?

**Comment by Crayjin** [comment]
You can easily fork LottieSharp and switching from .NET 4.6.1 to .NET 4.6 as far as I know. The sample app is working with .NET 4.6, but I don't know if there are any rare issues coming with it.

@OmidID Do you know any reason why using .NET 4.6 could be an issue?

**Comment by OmidID** [comment]
It's should work without any problem on 4.6 if we the dependencies from the nuget packages has no problem with 4.6

**Comment by MarcIsele** [comment]
Thanks, I created a fork and so far everything seems to work fine. https://github.com/MarcIsele/LottieSharp
