### ISSUE TITLE
Load Animation Error

### ISSUE THREAD

**Issue by Azyyyyyy** [quicoli/LottieSharp#14]
**Describe the bug**
Animation doesn't show after loading another animation

**To Reproduce**
Steps to reproduce the behaviour:
1. Start LottieSharp.Sample
2. Click on Load Animation
3. Click on another animation file
4. Animation isn't showing on the screen

**Expected behaviour**
After loading a new animation it would show the new animation on the screen

**Desktop:**
 - OS: Windows 10 17763.437

**Comment by OmidID** [comment]
Strange. We don't have this problem here!

**Comment by Crayjin** [comment]
Does the initial animation show up when starting the sample application? If not, it may be a graphics card driver issue and you should try to update as the generic driver seems to have issues.

**Comment by Azyyyyyy** [comment]
Yeah the initial animation does load up but I am not the up-to-date driver for my GPU (Nivida 1050Ti). I'll update it now and see if that does the trick

**Comment by Crayjin** [comment]
@AzyIsCool: If you are using an laptop, I don't think your dedicated GPU is being used but your integrated GPU. If this is your only GPU, then I'm not really convinced that an driver update will help.

**Comment by Azyyyyyy** [comment]
Nope, using desktop and updating the drivers did nothing. I don't see why it doing it ¯\_(ツ)_/¯

**Comment by Azyyyyyy** [comment]
Huh, ok now out of the blue it's working fine, well I don't what made it not work in the first place but if it's working now then I guess it must have been something else messing with it
