### ISSUE TITLE
CPU and GPU usage

### ISSUE THREAD

**Issue by Azyyyyyy** [quicoli/LottieSharp#15]
**Describe the bug**
Using more CPU and GPU usage that it should when animation is paused/cancelled

**To Reproduce**
Steps to reproduce the behaviour:
1. Start LottieSharp.Sample
2. Click on Pause Animation
4. CPU and GPU usage is higher then it should be

**Expected behaviour**
CPU and GPU usage should be lower then it is when animation is running

**Desktop (please complete the following information):**
 - OS: Windows 10 17763.437

**Additional context**
Mainly GPU usage should be lower when paused because it isn't doing any animating

**Comment by OmidID** [comment]
@AzyIsCool Actually not because it's rendering the current frame. when you pause the animation you only pausing the animation progress not rendering and you can see the GPU usage because of rendering not animating

**Comment by Azyyyyyy** [comment]
Maybe have a way to make the current frame a bitmap or a DrawingImage when paused then to allow usage to be lower because I know that they basically use nothing on CPU and GPU usage?

**Comment by OmidID** [comment]
No. Not possible. Because you are able to change the animation progress manually.
This is the example https://lottiefiles.com/684-progress-loading
