### ISSUE TITLE
Change colour through code

### ISSUE THREAD

**Issue by Azyyyyyy** [quicoli/LottieSharp#16]
**Is your feature request related to a problem? Please describe.**
In the Airbnb version you can change the colours that are in the animation, it would be great if we could do it through code and not have to edit the json file for the new colour

**Describe the solution you'd like**
Some way to change the colours of the animation in code and not with editing the json file

**Describe alternatives you've considered**
editing colour in json file before loading animation (how I'm doing it right now)

**Comment by ShankarBUS** [comment]
It would be great to have this feature
