### ISSUE TITLE
Missing values for keyframe.

### ISSUE THREAD

**Issue by royben** [quicoli/LottieSharp#17]
Trying to load this animation:
https://lottiefiles.com/5901-gradient-loading-icon

Got this exception when the application starts:
System.InvalidOperationException: 'Missing values for keyframe.'

From what I could understand, the issue relates to newer versions of Lottie files.

Please advise...

**Comment by Crayjin** [comment]
Hi, the animation link does not work. Please provide a working link.

**Comment by royben** [comment]
Please try again, It is working now. That website was down for a few minutes.

**Comment by aleksey-shubin** [comment]
Having the same issue. Looks like it's caused by the new json format in bodymovin 5.5. Do you plan to add support for the new format?

**Comment by Crayjin** [comment]
In the meantime, if you are the one creating the animation, you can try to export it with the old format in advanced mode (Settings > Advanced > Export Old Json Format, Source: https://github.com/airbnb/lottie-web/issues/1561).

**Comment by savemysoul382** [comment]
Having the same issue. Almost all animations in https://lottiefiles.com/marketplace don`t work. 
looking forward to the new version. Thank you.

**Comment by OmidID** [comment]
Looks you right. I can see the protocol updated. Mybe that animation get failed to run.
@Crayjin Any plan for update?

**Comment by Crayjin** [comment]
@OmidID There is no update planned from my side.

**Comment by Gilardeau** [comment]
Same issue too,

I installed the 1.0.0 version, witch version should i install to get the lasted commit how include the support for new Bodymovin 5.5 keyframes ? ( 12 jul ) 

Thanks
