### ISSUE TITLE
App exit with exception

### ISSUE THREAD

**Issue by Leon-Zhang** [quicoli/LottieSharp#19]
**Describe the bug**
Lottie animation crashes WPF application

**To Reproduce**
Just run lottie animation and wait, application will crash.

**Expected behavior**
The program '[0x192B4] Seekadoo.exe' has exited with code -1073740791 (0xc0000409).

**Desktop (please complete the following information):**
 - OS: Windows10

**Additional context**
Visual Studio 2017

**Comment by Crayjin** [comment]
Hi, please check if the sample application will crash with your animation too. If not, please provide your own sample application, so we can debug the issue.
