### ISSUE TITLE
Application Failed to Run

### ISSUE THREAD

**Issue by AdarshRise** [quicoli/LottieSharp#21]
![image](https://user-images.githubusercontent.com/31347367/63649900-1a639600-c761-11e9-9dbd-3fb3b61f9567.png)
![image](https://user-images.githubusercontent.com/31347367/63649906-3b2beb80-c761-11e9-942d-805e485a3892.png)

**Comment by AdarshRise** [comment]
Fresh application, after installing the Nuget package. still failed.

**Comment by OmidID** [comment]
Thank you for using LottieSharp
This package is compatible with WPF only and i can see you have universal app

**Comment by AdarshRise** [comment]
It's WPF, And I named it as "FakeUWPanime" because, I thought only UWP is being supported. When I found Lottiesharp I tried to use it and ended up as the "screenshots" shows. Same exception showed up in the sample/demo which is present in this repository.

**Comment by OmidID** [comment]
Are you loading any specific animation? Or did you try to download the source and run it with default animation?

**Comment by AdarshRise** [comment]
I downloaded a json file from the Lottie website, and as you can see  the same is present in the first screenshot" strong lock.json".

**Comment by Crayjin** [comment]
Hi, is the json file copied into the debug/release folder?

**Comment by AdarshRise** [comment]
Yeah, thanks, it works now, But the designer still shows NullReferenceException. I still want to see the designer to work properly on UI.

**Comment by OmidID** [comment]
It looks a bug in the designer. We have skipping codes for the designer and I'll check it again.

**Comment by ammelto** [comment]
I encountered this issue too, my work around is just setting the FileName property on your AnimationView in the code. In my experience, the designer has trouble finding relative paths if you aren't using a pack URI but since LottieSharp doesnt support pack URIs (maybe a feature request 😄) you should convert the relative path into an absolute path at runtime then pass it to the animation view.
