### ISSUE TITLE
Event for when animation is done

### ISSUE THREAD

**Issue by alkies** [quicoli/LottieSharp#24]
Nice plugin for Windows Form applications.

I'm not sure if this feature already exists, but it would be nice to get a event when the animation is finished.

**Comment by ShankarBUS** [comment]
Is this project still alive? or is it being kept on maintenance? I would love to hear that this project is still alive 😁. This project is the only solution of bringing WPF apps into the Lottie family. I don't want to use WinUI or xaml islands just for rendering Lottie.
