### ISSUE TITLE
Animation disappears when computer is locked and then unlocked

### ISSUE THREAD

**Issue by Hanawa02** [quicoli/LottieSharp#25]
**Describe the bug**
After an app with an animation is started, if the user locks the computer, when the computer is unlocked (even after a few seconds) the animation is not shown anymore.

**To Reproduce**
1. Start an app with animation (check if animation is visible and running)
2. lock your computer
3. unlock your computer
4. the animation will is not showed anymore

**Expected behavior**
The animation would be displayed.

**Screenshots**
Before locking the computer:
![image](https://user-images.githubusercontent.com/11237366/70527132-781ec100-1b4b-11ea-94b8-14cd09639fd4.png)

After unlocking the computer:
![image](https://user-images.githubusercontent.com/11237366/70527157-8ec51800-1b4b-11ea-859e-26be4d6e1e92.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser : N/A
 - Version: v4.0.30319

**Additional context**
The animation has no state where nothing is visible.

**Comment by cmo-thoughtworks** [comment]
Hello,

I was able to reproduce this same issue regarding the animation for an application we've been working on as well.  To expand on the described bug (the animation disappearing after a user locks/unlocks the computer screen), it looks like any screen overlay (i.e. in our case, a Windows UAC prompt) causes the animation to disappear as well.  

Is there a plan or roadmap in the works to address this bug?

**Comment by OmidID** [comment]
@Crayjin WindowChrome bug was fixed too.
