### ISSUE TITLE
Pack Uri is not work

### ISSUE THREAD

**Issue by TheDawnCc** [quicoli/LottieSharp#28]
**Describe the bug**
The LottieView is not support the pack uri like "pack://siteoforigin,,,/Resources/Lottie/xxx.json".I got blank by this way.
**To Reproduce**
1. Load the lottieview
2. The lottieview show blank window

**Comment by ajaywhiz** [comment]
Do we have any update on this? Don't want to expose the json

**Comment by OmidID** [comment]
There are several methods that you could use like `SetAnimationAsync` or `SetAnimationFromJsonAsync` to load the file content directly for the moment the pack uri is not supported

**Comment by ajaywhiz** [comment]
Yes. That's what I did

```csharp
string imagePath = "[Pack URI]";
StreamResourceInfo imageInfo = System.Windows.Application.GetResourceStream(new Uri(imagePath));
StreamReader sr = new StreamReader(imageInfo.Stream);
var animationJson = sr.ReadToEnd();
sr.Close();
await LottieAnimationView.SetAnimationFromJsonAsync(animationJson, "Spinner");

```

Any ETA on when it will be supported?

Regards,
Ajay
