### ISSUE TITLE
Message: 位图像素格式不受支持

### ISSUE THREAD

**Issue by whnpneo** [quicoli/LottieSharp#30]
eg:https://assets7.lottiefiles.com/packages/lf20_laffnn.json

SharpDX.SharpDXException
  HResult=0x88982F80
  Message=HRESULT: [0x88982F80], Module: [SharpDX.Direct2D1], ApiCode: [D2DERR_UNSUPPORTED_PIXEL_FORMAT/UnsupportedPixelFormat], Message: 位图像素格式不受支持。

  Source=SharpDX

**Comment by whnpneo** [comment]
screenshot
![微信截图_20200611143641](https://user-images.githubusercontent.com/38681789/84353125-2685ea80-abf1-11ea-84c3-ee2030d9e4d6.png)

**Comment by OmidID** [comment]
Will be fixed in next update
