### ISSUE TITLE
When including this nuget to project with strongly name it generates warning

### ISSUE THREAD

**Issue by marik91** [quicoli/LottieSharp#33]
When using this nuget withing strongly named assembly project it generates warning that LottieSharp assembly does not have strong name. 
    Warning CS8002: Referenced assembly 'LottieSharp, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

Can you sign this nuget with [strong name](https://docs.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name)?

**Comment by OmidID** [comment]
For the next release I'll add it.

**Comment by marik91** [comment]
Thanks 👍 hope it will be released soon :)

**Comment by OmidID** [comment]
New package from nuget has signed assembly.
