### ISSUE TITLE
Refresh problem

### ISSUE THREAD

**Issue by AlessandroMiorelli** [quicoli/LottieSharp#38]
I'm testing your library, but I have refresh problem
Try this json
[LT-Test_noLogo.zip](https://github.com/ascora/LottieSharp/files/5360824/LT-Test_noLogo.zip)

This is the result
![immagine](https://user-images.githubusercontent.com/33350344/95674848-2acc0f80-0bb3-11eb-8c45-e9e591c834bc.png)

Regards
Alessandro

**Comment by wangjinming01** [comment]
public Disposable PushMask(RectangleF rect, float alpha, Path path = null)
        {
            if (alpha >= 1 && path == null)
            {
                //CurrentRenderTarget.PushAxisAlignedClip(rect, CurrentRenderTarget.AntialiasMode);

                return new Disposable(() =>
                {
                    //CurrentRenderTarget.PopAxisAlignedClip();
                });
            }
Comment two lines ,it works ok.

**Comment by AlessandroMiorelli** [comment]
Thank you @wangjinming01, it works.
Another question, if I have two LottieAnimationView on the same form and I load the same json I have this exception 

SharpDX.SharpDXException: 'HRESULT: [0x88990012], Module: [SharpDX.Direct2D1], ApiCode: [D2DERR_WRONG_FACTORY/WrongFactory], Message: Objects used together must be created from the same factory instance. 

This doesn't occur if I load different json.

I found an old post, maybe about that, but I don't undestand the solution.

Thank you
