### ISSUE TITLE
SharpDX no longer maintained

### ISSUE THREAD

**Issue by dbischoff1** [quicoli/LottieSharp#42]
I'm considering using LottieSharp in a .NET Framework / WPF application. LottieSharp depends on SharpDX which does not seem to be maintained anymore (see https://github.com/sharpdx/SharpDX). Are there any plans to address this in the future?

Kind Regards
Daniel

**Comment by OmidID** [comment]
Yes already I know about it.
If you check other issues you will see that I want to migrate it to maybe skia sharp. But better say not soon

**Comment by dbischoff1** [comment]
Ok. Thank you!
