### ISSUE TITLE
Texts elements shifted

### ISSUE THREAD

**Issue by AntoineBouquetSully** [quicoli/LottieSharp#44]
Hello,

after using this plugin in a WPF project, we saw that texts elements of the Lottie json file are shifted to the right, compare to the real animation.

For exemple, we have [this animation](https://lottiefiles.com/share/u4pdi0fv) that "Lottie" text appeared at the bottom right corner.

When this JSON is used with LottieSharp, there is the same animated frame but the text "Lottie" is shift to right, as we can see in the picture below representing the last frame of the animation.

![test1](https://user-images.githubusercontent.com/67469878/110963445-5d408b00-8352-11eb-92ac-d787403cb0b8.PNG)

There is a solution to this ? Or this a bug to fix ?

Thanks in advance for your time

Antoine

**Comment by OmidID** [comment]
Hello, I imagine this is new animation.
So we didn't update it for long time and maybe if you can export it with the older version of bodymovin if possible for you.

**Comment by AntoineBouquetSully** [comment]
Hi, thanks for your answer.

What do you mean by "new animation" and "older version"?
What older version of Lottie After Effect Plugin do you think it must be used for fix this bug? 

If I understand well, versions of this plugin could be found here : https://github.com/airbnb/lottie-web/tags

Besides, do you think a fix is possible to LottieSharp in order to use new and old animation with texts? I have not looked at the code of this plugin yet but maybe can I suggest to you a PR if it is not too complicated?

**Comment by OmidID** [comment]
Sorry for late,
You know this project had no update on the protocol over 2 years and I cannot mention by version id or tag id. 

And you are welcome to help to maintain and update it as well.
