### ISSUE TITLE
LottieSharp Logo

### ISSUE THREAD

**Issue by OmidID** [quicoli/LottieSharp#5]
@Crayjin How do you think about this logo?
![image](https://user-images.githubusercontent.com/956077/51400985-678be380-1b52-11e9-98b6-0c44405129d9.png)

**Comment by Crayjin** [comment]
It looks good. Maybe making the #-symbol more straight/sharp as a contrast to the cursive L like that? Maybe using the round ends of the #-symbol.

![lottiesharp](https://user-images.githubusercontent.com/24563614/51403257-39a59f80-1b50-11e9-94a4-01d9b9b52ee9.jpg)

**Comment by OmidID** [comment]
@Crayjin Something like this?
![image](https://user-images.githubusercontent.com/956077/51412684-088b9600-1b75-11e9-8dbc-2181f8bd7f14.png)

**Comment by Crayjin** [comment]
Very nice!

**Comment by SvenAbels** [comment]
Great :-)

**Comment by OmidID** [comment]
:) So, I going to export it ;)
