### ISSUE TITLE
Object reference not set to an instance of an object at LottieSharp.LottieAnimationView

### ISSUE THREAD

**Issue by fahmi-dzulqarnain** [quicoli/LottieSharp#50]
**Describe the bug**
I got an error when add File Name on LottieAnimationView. It produce NullReferenceException: Object reference not set to an instance of an object at LottieSharp.LottieAnimationView.set_Composition(LottieComposition value) at LottieSharp.LottieAnimationView.<SetAnimationAsync>d__59.MoveNext()

![image](https://user-images.githubusercontent.com/60492666/132240756-cb9300b2-e137-4552-896b-325d8fde0156.png)

Thanks

**Comment by saklanmazozgur** [comment]
I have the same problem, did you find a solution?

**Comment by jm-parent** [comment]
Hey ! 

Had the same issue.

1 - Put your json in solution 
![image](https://user-images.githubusercontent.com/39386863/138468915-04fa9c25-0cea-4859-b890-c750e2fb2e0c.png)

2 - Check settings 
![image](https://user-images.githubusercontent.com/39386863/138468972-251f8293-9a17-4c26-839f-d779c1bd5db7.png)

3 - Check your .csproj and find the new line 
![image](https://user-images.githubusercontent.com/39386863/138468750-79e03fba-88bc-4709-835f-94bc279c9ac7.png)

4 - Update your xaml 
![image](https://user-images.githubusercontent.com/39386863/138469095-301dd0ae-1e49-4255-8b2b-be94879f531f.png)

Thats how i fix mine :) 

Hope it will help you too

**Comment by fahmi-dzulqarnain** [comment]
Not solve my issue

**Comment by fahmi-dzulqarnain** [comment]
Give another issue:

SharpDX.SharpDXException: 'HRESULT: [0x88990012], Module: [SharpDX.Direct2D1], ApiCode: [D2DERR_WRONG_FACTORY/WrongFactory], Message: Objects used together must be created from the same factory instance.
'

**Comment by fahmi-dzulqarnain** [comment]
Thank you
