### ISSUE TITLE
 Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by sarahBenzaquen** [quicoli/LottieSharp#54]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I need to use a json to make a gif , and when i put the control in my page the error " Object reference not set to an instance of an object" appears , my json is ok i have tried it like embedded resources and also content and it's not working, I don't know how to solve this please

**Comment by strathdeek** [comment]
You need to set the build action to none, and select "copy to output directory"

**Comment by keytrap-x86** [comment]
I think that if you look closely to the errors, you will see the same error:

![image](https://user-images.githubusercontent.com/17864005/175697152-ec2b4a4a-e398-4fc8-b40d-cb4dbe3362b8.png)

The null reference exception comes after the first one so the real error is that the lottie viewer cannot find your .JSON file :

![image](https://user-images.githubusercontent.com/17864005/175697214-e20f7217-7691-4994-b4f8-f58150c8a580.png)

Try to remove the first slash from path:

![image](https://user-images.githubusercontent.com/17864005/175697318-0e7a028e-79d3-48a3-906b-0d2198d1bc28.png)

So it's like this:

![image](https://user-images.githubusercontent.com/17864005/175697345-81bf4ccb-910e-4bec-a4d0-96b22a483ab3.png)

And set the properties of the .json file to this:

![image](https://user-images.githubusercontent.com/17864005/175697488-f2e2b5af-94d5-46b6-a688-48a023a3c37d.png)
