### ISSUE TITLE
The Proyect does't compile

### ISSUE THREAD

**Issue by ElMaldithoDJ** [quicoli/LottieSharp#6]
Hellow Is this project funcional in WPF or is only a fake delution?

**Comment by OmidID** [comment]
Hellow! 
That's all? No any activity at github except this stupid comment?
If you don't have enough knowledge to compile it use nuget package if you know what is the nuget

**Comment by ElMaldithoDJ** [comment]
@OmidID Yes my friend I know it but if you want to help me pleace because I Try but VS reporting me this
**unable to parse composition** I would appreciate that someone help me to how can I use it

**Comment by ElMaldithoDJ** [comment]
and @OmidID don't write like **this stupid comment** it offends me, If you want to help me, help please but don't write that beacuse you don't know if you need someone in the furture that help you and Im the person that you need to help you

**Comment by OmidID** [comment]
@ElMaldithoDJ If you need help you need to write description what is your problem not asking unexpected questions (fake delution ????) do you think is not offends us? !!! even you didn't pay attention to the typo. 
If you need help you need to write your problem with details. Build output or error(s) you have.

**Comment by ElMaldithoDJ** [comment]
@OmidID  Ok my friend I going to put a image to help me

**Comment by ElMaldithoDJ** [comment]
### **Design view broken**
![a2](https://user-images.githubusercontent.com/24962990/51856429-12945e00-2306-11e9-800c-3b84478f3642.jpg)

@OmidID 
In English is: **NullReferenceException: Object reference not set to an instance of an object**
What can I do on that case?

**Comment by OmidID** [comment]
Please paste your output detail or tell me at which line you get this error?
Also please paste part of your code how you are using that in your project

**Comment by ElMaldithoDJ** [comment]
@OmidID  Can you give me your email to send my code to you?

**Output**
![out](https://user-images.githubusercontent.com/24962990/52169327-8a022d00-270c-11e9-919d-ab74cd0327ae.jpg)

Code & Design mode
![code design mode](https://user-images.githubusercontent.com/24962990/52169384-c2563b00-270d-11e9-888d-b2655602b73d.jpg)

**Comment by andrebbk** [comment]
Same error here when I try to display a lottie animation!
Specific when I add this line - FileName="file_animation.json"

![Capture](https://user-images.githubusercontent.com/37023197/65696001-695a5f00-e070-11e9-808c-1bb2626f8e0f.PNG)

Did you find a solution for this?

**Comment by DanaBear** [comment]
Any solution to this? I have the same issue.
