### ISSUE TITLE
Exception on unsupported device

### ISSUE THREAD

**Issue by Crayjin** [quicoli/LottieSharp#9]
It would be good, if the exception would be handled more gracefully. Unfortunately this has been only reported to me, so I cannot reproduce it by myself.

Occurred on Microsoft Windows 7 Professional , 32-Bit, Service Pack 1, Version 6.1.7601, Build 7601

```
UNHANDLED EXCEPTION: SharpDX.SharpDXException: HRESULT: [0x887A0004], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_UNSUPPORTED/Unsupported], Message: Unknown
bei SharpDX.Result.CheckError()
bei SharpDX.Direct3D11.Device.CreateDevice(Adapter adapter, DriverType driverType, DeviceCreationFlags flags, FeatureLevel[] featureLevels)
bei LottieSharp.WpfSurface.D2dControl.StartD3D()
bei LottieSharp.WpfSurface.D2dControl.Window_Loaded(Object sender, RoutedEventArgs e)
bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
bei System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
bei System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
bei System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
bei MS.Internal.LoadedOrUnloadedOperation.DoWork()
bei System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
bei System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
bei System.Windows.Media.MediaContext.Rend
```

**Comment by Crayjin** [comment]
The debug flag may help:

`d3d11Device = new SharpDX.Direct3D11.Device(DriverType.Hardware, DeviceCreationFlags.Debug);`

Source: http://sharpdx.org/wiki/usage/

That exception will not be thrown in the sample application but the animation is then just not visible.

**Comment by Crayjin** [comment]
It seems that the issue are defect or default graphics card driver. After an update some issues (exceptions) disappeared.

**Comment by quicoli** [comment]
Issue #12 request a better exception handling... I think we can close this #9 since it probably will be covered  on #12, what do you think?

**Comment by Crayjin** [comment]
Yes, I think so too.

Additionally, the error I encountered was due to missing/wrong graphic cards driver. So if anyone has the same issue, try to update driver and/or Windows updates (optional updates can provide graphic cards driver too).
